#!/usr/bin/env bash
# server-setup.sh — one-shot provisioning for a fresh Ubuntu droplet
#
# Usage:
#   bash scripts/server-setup.sh <domain> <github-repo-url>
#
# Example:
#   bash scripts/server-setup.sh notes.example.com https://github.com/you/note-scan
#
# What it does:
#   1. Installs Docker, nginx, certbot, git
#   2. Clones your repo to /opt/notescan
#   3. Prompts you for secrets and writes /opt/notescan/.env
#   4. Configures nginx and gets a Let's Encrypt certificate
#   5. Builds and starts the app with docker compose
#
# Run as root or a user with sudo.

set -euo pipefail

# ─── Args ─────────────────────────────────────────────────────────────────────

DOMAIN="${1:-}"
REPO_URL="${2:-}"
APP_DIR=/opt/notescan

if [[ -z "$DOMAIN" || -z "$REPO_URL" ]]; then
  echo "Usage: $0 <domain> <github-repo-url>"
  echo "  e.g. $0 notes.example.com https://github.com/you/note-scan"
  exit 1
fi

# Run as root; if not, re-exec with sudo
if [[ "$EUID" -ne 0 ]]; then
  exec sudo -E bash "$0" "$@"
fi

# ─── Helpers ──────────────────────────────────────────────────────────────────

info()    { echo -e "\033[1;34m[setup]\033[0m $*"; }
success() { echo -e "\033[1;32m[setup]\033[0m $*"; }
prompt()  { read -rp $'\033[1;33m[input]\033[0m '"$1"': ' "$2"; }
prompt_secret() { read -rsp $'\033[1;33m[input]\033[0m '"$1"' (hidden): ' "$2"; echo; }

# ─── 1. System packages ───────────────────────────────────────────────────────

info "Updating system packages..."
apt-get update -qq
apt-get install -y -qq curl git nginx certbot python3-certbot-nginx ufw

# ─── 2. Docker ────────────────────────────────────────────────────────────────

if ! command -v docker &>/dev/null; then
  info "Installing Docker..."
  curl -fsSL https://get.docker.com | sh
  systemctl enable docker
  systemctl start docker
else
  info "Docker already installed — skipping"
fi

# ─── 3. Clone repo ────────────────────────────────────────────────────────────

if [[ -d "$APP_DIR/.git" ]]; then
  info "Repo already cloned at $APP_DIR — pulling latest..."
  git -C "$APP_DIR" pull origin main
else
  info "Cloning $REPO_URL → $APP_DIR..."
  git clone "$REPO_URL" "$APP_DIR"
fi

# ─── 4. Create .env ───────────────────────────────────────────────────────────

ENV_FILE="$APP_DIR/.env"

if [[ -f "$ENV_FILE" ]]; then
  info ".env already exists — skipping interactive setup"
  info "Edit $ENV_FILE manually if you need to change secrets"
else
  info "Generating .env — you'll be prompted for secrets now"
  echo ""

  NEXTAUTH_SECRET=$(openssl rand -base64 32)
  info "NEXTAUTH_SECRET auto-generated"

  prompt "GOOGLE_CLIENT_ID"     GOOGLE_CLIENT_ID
  prompt_secret "GOOGLE_CLIENT_SECRET" GOOGLE_CLIENT_SECRET
  prompt_secret "ANTHROPIC_API_KEY"    ANTHROPIC_API_KEY

  echo ""
  info "Optional — press Enter to keep defaults shown in []"

  read -rp $'\033[1;33m[input]\033[0m OCR_PROVIDER [anthropic]: ' OCR_PROVIDER
  OCR_PROVIDER="${OCR_PROVIDER:-anthropic}"

  read -rp $'\033[1;33m[input]\033[0m MONTHLY_BUDGET_CENTS [2000]: ' MONTHLY_BUDGET_CENTS
  MONTHLY_BUDGET_CENTS="${MONTHLY_BUDGET_CENTS:-2000}"

  cat > "$ENV_FILE" <<EOF
# Generated by server-setup.sh — do not commit this file
NEXTAUTH_URL=https://${DOMAIN}
NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
NODE_ENV=production

GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}

OCR_PROVIDER=${OCR_PROVIDER}
ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
ANTHROPIC_MODEL=claude-haiku-4-5-20251001
OCR_CONCURRENCY=5

MONTHLY_BUDGET_CENTS=${MONTHLY_BUDGET_CENTS}
RATE_LIMIT_PAGES_PER_HOUR=60
RATE_LIMIT_PAGES_PER_DAY=300
MAX_PAGES_PER_BATCH=30

DATABASE_URL=file:/data/notescan.db
EOF

  chmod 600 "$ENV_FILE"
  success ".env written to $ENV_FILE"
fi

# ─── 5. nginx ─────────────────────────────────────────────────────────────────

NGINX_SITE=/etc/nginx/sites-available/notescan

info "Configuring nginx for $DOMAIN..."

# Write the HTTP-only config first (Certbot will upgrade it to HTTPS)
cat > "$NGINX_SITE" <<EOF
server {
    listen 80;
    server_name ${DOMAIN};

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        proxy_pass http://127.0.0.1:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        client_max_body_size 50M;
        proxy_read_timeout 120s;
        proxy_send_timeout 120s;
    }
}
EOF

ln -sf "$NGINX_SITE" /etc/nginx/sites-enabled/notescan
rm -f /etc/nginx/sites-enabled/default

nginx -t
systemctl enable nginx
systemctl reload nginx

success "nginx configured"

# ─── 6. Firewall ──────────────────────────────────────────────────────────────

info "Configuring ufw firewall..."
ufw --force enable
ufw allow OpenSSH
ufw allow "Nginx Full"
success "Firewall rules applied"

# ─── 7. TLS certificate ───────────────────────────────────────────────────────

info "Requesting Let's Encrypt certificate for $DOMAIN..."
info "Make sure your domain's A record points to this server's IP before continuing."
echo ""
read -rp $'\033[1;33m[input]\033[0m Your email for Let'\''s Encrypt expiry notices: ' LE_EMAIL

certbot --nginx \
  --non-interactive \
  --agree-tos \
  --email "$LE_EMAIL" \
  -d "$DOMAIN"

# Certbot rewrites the nginx config — add security headers to the HTTPS block
# by appending an include snippet
SNIPPET=/etc/nginx/snippets/notescan-headers.conf
cat > "$SNIPPET" <<'EOF'
add_header Strict-Transport-Security "max-age=63072000; includeSubDomains" always;
add_header X-Content-Type-Options nosniff;
add_header X-Frame-Options SAMEORIGIN;
add_header Referrer-Policy strict-origin-when-cross-origin;
EOF

# Inject the include into the 443 server block if not already there
if ! grep -q "notescan-headers" "$NGINX_SITE"; then
  sed -i '/listen 443/a\    include snippets/notescan-headers.conf;' "$NGINX_SITE"
fi

nginx -t && systemctl reload nginx
success "TLS certificate obtained and nginx reloaded"

# ─── 8. Build and start the app ───────────────────────────────────────────────

info "Building and starting the app (this takes a few minutes)..."
cd "$APP_DIR"
docker compose up --build -d

success "App started"
echo ""

# ─── 9. Summary ───────────────────────────────────────────────────────────────

success "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
success " NoteScan is live at https://${DOMAIN}"
success "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Next steps:"
echo "  • Add https://${DOMAIN}/api/auth/callback/google as an"
echo "    authorized redirect URI in Google Cloud Console"
echo "  • Check app logs: docker compose -f $APP_DIR/docker-compose.yml logs -f"
echo "  • Check nginx:    journalctl -u nginx -f"
echo ""
echo "Auto-deploy via GitHub Actions:"
echo "  Add these secrets to your GitHub repo (Settings → Secrets):"
echo "    DROPLET_HOST = $(curl -s ifconfig.me 2>/dev/null || echo '<your-server-ip>')"
echo "    DROPLET_USER = root"
echo "    DROPLET_SSH_KEY = <contents of your deploy private key>"
